[2025-03-18T09:21:40.363+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-18T09:21:40.400+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_etl_dag.transform_data scheduled__2025-03-18T08:00:00+00:00 [queued]>
[2025-03-18T09:21:40.410+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_etl_dag.transform_data scheduled__2025-03-18T08:00:00+00:00 [queued]>
[2025-03-18T09:21:40.410+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-18T09:21:40.423+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2025-03-18 08:00:00+00:00
[2025-03-18T09:21:40.436+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'amazon_etl_dag', 'transform_data', 'scheduled__2025-03-18T08:00:00+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp1vfgp28_']
[2025-03-18T09:21:40.438+0000] {standard_task_runner.py:91} INFO - Job 263: Subtask transform_data
[2025-03-18T09:21:40.439+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=70058) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-18T09:21:40.440+0000] {standard_task_runner.py:63} INFO - Started process 70086 to run task
[2025-03-18T09:21:40.480+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_etl_dag.transform_data scheduled__2025-03-18T08:00:00+00:00 [running]> on host 23e83e453497
[2025-03-18T09:21:40.549+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_etl_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-18T08:00:00+00:00'
[2025-03-18T09:21:40.550+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-18T09:21:40.635+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-03-18T09:21:42.186+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-03-18T09:21:43.515+0000] {logging_mixin.py:188} INFO - Random Forest MSE: 182049167.8207299 - R²: 0.7915716146596294
[2025-03-18T09:21:43.516+0000] {logging_mixin.py:188} INFO - XGBoost MSE: 260755454.64037323 - R²: 0.70146066016129
[2025-03-18T09:21:43.528+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/transform.py:88 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-18T09:21:43.551+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-03-18T09:21:43.551+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-18T09:21:43.559+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=amazon_etl_dag, task_id=transform_data, run_id=scheduled__2025-03-18T08:00:00+00:00, execution_date=20250318T080000, start_date=20250318T092140, end_date=20250318T092143
[2025-03-18T09:21:43.585+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-18T09:21:43.604+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-18T09:21:43.606+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
